# This is a generated file. Not intended for manual editing.
services:
  catalog.api:
    build:
      context: "C:\\Users\\danie\\RiderProjects\\Microsservices"
      dockerfile: "Catalog.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/Catalog.API.dll"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net8.0/Catalog.API.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "catalog.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\danie\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\danie\\RiderProjects\\Microsservices\\Catalog.API:/app:rw"
    - "C:\\Users\\danie\\RiderProjects\\Microsservices:/src:rw"
    working_dir: "/app"
