services:
  catalogdb:
    image: mongo
    container_name: catalogdb
    restart: always
    ports:
        - "27017:27017"
    volumes:
        - mongo_data:/data/db
  
  
  catalog.api:
    image: catalog.api
    container_name: catalog.api
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
        - catalogdb
    ports:
        - "8000:8080"
    build:
      context: .
      dockerfile: Catalog.API/Dockerfile

volumes: 
  mongo_data: